# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

steps:

- task: PowerShell@2
  condition: succeeded()
  displayName: Find packages folder
  inputs:
    targetType: 'inline'
    script: |
      
      $solutionLocation = (Get-ChildItem -Path "$(Build.SourcesDirectory)" -Include $(solution) -Recurse)
      $packagesLocation = $solutionLocation[0].Directory.FullName+"\packages"

      Write-Host "Found packages folder for solution at: $packagesLocation"

      echo "##vso[task.setvariable variable=NUGET_PACKAGES]$packagesLocation"

- task: Cache@2
  displayName: Cache NuGet packages
  condition: succeeded()
  inputs:
    key: 'nuget | **/packages.lock.json'
    path: $(NUGET_PACKAGES)
