# Copyright (c) 2018 The nanoFramework project contributors
# Portions Copyright (c) Sankarsan Kampa (a.k.a. k3rn31p4nic).  All rights reserved.
# See LICENSE file in the project root for full license information.

parameters:
  skipNuGetRestore: false
  gitUser: 'nfbot'
  gitEmail: 'nanoframework@outlook.com'
  sonarCloudProject: 'dummy-key'
  nugetConfigPath: 'source/NuGet.config'
  msbuildExtraParams: ' '

steps:
# need this here in order to persist GitHub credentials 
- checkout: self

- script: |
    git config --global user.email ${{ parameters.gitEmail }}
    git config --global user.name ${{ parameters.gitUser }}
    git config --global core.autocrlf true
  displayName: Setup git identity

# get commit message
- powershell: |

    if($env:Build_SourceBranch -like "refs/pull*")
    {
      # PR build, get PR message

      # need to get PR number from branch as the Azure Pipeline var can't be trusted
      if($env:Build_SourceBranch -match '(?<=(pull\/))\w*(?=(\/))')
      {
        $prNumber = $matches[0]

        $prUrl = "https://api.github.com/repos/$env:Build_Repository_Name/pulls/$prNumber"

        $commit = Invoke-RestMethod -Uri $prUrl -ContentType "application/json" -Method GET

        $commitMessage = $commit.body
      }
    }
    else
    {
      # not a PR, get subject and commit message for commit
      $commitMessage = git log --format='%B' -1
    }

    # need to flatten message by removing new lines
    $commitMessage = $commitMessage -replace "`r`n", " "

    # set variable to foward to jobs
    echo "##vso[task.setvariable variable=COMMIT_MESSAGE;isOutput=true]$commitMessage"
  name: getCommitMessage
  displayName: grab commit message

- task: DotNetCoreCLI@2  
  inputs:
    command: custom
    custom: tool
    arguments: install -g nbgv
  condition: or( eq( variables['StartReleaseCandidate'], true ), ne(variables['system.pullrequest.isfork'], true) )
  displayName: Install NBGV tool

- powershell: |
    # compute authorization header in format "AUTHORIZATION: basic 'encoded token'"
    # 'encoded token' is the Base64 of the string "nfbot:personal-token"
    $auth = "basic $([System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("nfbot:$(GitHubToken)"))))"

    cd "$env:Agent_TempDirectory" > $null

    Write-Host "Cloning from: $env:BUILD_REPOSITORY_URI"

    git clone $env:BUILD_REPOSITORY_URI repo
    cd repo > $null
    git config --global gc.auto 0
    git config --global user.name nfbot
    git config --global user.email nanoframework@outlook.com
    git config --global core.autocrlf true
    
    Write-Host "Checkout develop branch..."
    git checkout --quiet develop  > $null

    # prepare release and capture output
    Write-Host "Prepare release with NBGV..."
    $release = nbgv prepare-release -p source

    Write-Host "Prepare commit..."
    # get commit message for the merge
    $commitMessage = git log -1 --pretty=%B

    # amend commit message to skip build
    git commit --amend -m "$commitMessage" -m "***NO_CI***" > $null

    Write-Host "Pushing changes to GitHub..."
    # push all changes to github
    git -c http.extraheader="AUTHORIZATION: $auth" push --quiet --all origin

    # get release branch name
    $branch = $release.Split(' ')[0]

    Write-Host "Prepare PR..."
    # start PR for release
    $prRequestBody = @{title="Release $branch";body="";head="$branch";base="master"} | ConvertTo-Json
    $githubApiEndpoint = "https://api.github.com/repos/$env:BUILD_REPOSITORY_NAME/pulls"
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

    $headers = @{}
    $headers.Add("Authorization","$auth")
    $headers.Add("Accept","application/vnd.github.symmetra-preview+json")

    try 
    {
        $result = Invoke-RestMethod -Method Post -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::InternetExplorer -Uri  $githubApiEndpoint -Header $headers -ContentType "application/json" -Body $prRequestBody
        'Started PR for new release...' | Write-Host -NoNewline
        'OK' | Write-Host -ForegroundColor Green
    }
    catch 
    {
        $result = $_.Exception.Response.GetResponseStream()
        $reader = New-Object System.IO.StreamReader($result)
        $reader.BaseStream.Position = 0
        $reader.DiscardBufferedData()
        $responseBody = $reader.ReadToEnd();

        "Error starting PR: $responseBody" | Write-Host -ForegroundColor Red
    }
  workingDirectory: $(Agent.TempDirectory)
  ignoreLASTEXITCODE: true
  condition: eq( variables['StartReleaseCandidate'], true )
  displayName: NBGV prepare release

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud-$(System.TeamProject)'
    organization: 'nanoframework'
    scannerMode: 'MSBuild'
    projectKey: '${{ parameters.sonarCloudProject }}'
  condition: ne( variables['StartReleaseCandidate'], true )
  displayName: 'Prepare analysis on SonarCloud'

- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '4.9.3'
  condition: ne( variables['StartReleaseCandidate'], true )
  displayName: 'Install specific version of NuGet'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: config
    nugetConfigPath: ${{ parameters.nugetConfigPath }}
  condition: and( succeeded(), not( ${{ parameters.skipNuGetRestore }} ), ne( variables['StartReleaseCandidate'], true ) )
  displayName: NuGet restore

- task: InstallnFBuildComponents@1
  condition: ne( variables['StartReleaseCandidate'], true )
  displayName: Install nanoFramework MSBuild components

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    msbuildArgs: '/p:PublicRelease=true ${{ parameters.msbuildExtraParams }}'
    configuration: '$(buildConfiguration)'
  condition: ne( variables['StartReleaseCandidate'], true )

# we don't have tests (yet)
# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
#   condition: ne( variables['StartReleaseCandidate'], true )

- task: PowerShell@2
  inputs:
      targetType: 'inline'
      script: |
          $MyNuGetVersion = $env:NBGV_NuGetPackageVersion -replace "\-g$env:NBGV_GitCommitIdShort", ""

          # replace preview with alpha if this is a PR build
          if($env:Build_Reason -eq 'PullRequest')
          {
            $MyNuGetVersion = $MyNuGetVersion -replace "preview", "alpha"
          }

          Write-Host "NuGet build number is $MyNuGetVersion"

          Write-Host "$("##vso[task.setvariable variable=MY_NUGET_VERSION]")$MyNuGetVersion"
  condition: and( succeeded(), ne( variables['StartReleaseCandidate'], true ) )
  displayName: Get NuGet build number

- task: PowerShell@2
  inputs:
      targetType: 'inline'
      script: |

          $assemblyInfoFiles = (Get-ChildItem -Path ".\*" -Include "AssemblyInfo.cs" -Recurse)
          $attributeRegex = '(AssemblyNativeVersion\(\")+(\d+\.\d+\.\d+\.\d)+("\))'

          $attributeRegex = [regex]"(AssemblyNativeVersion\(\"")+(\d+\.\d+\.\d+\.\d)+(""\))"

          # read attribute from file
          $fileContent = Get-Content($assemblyInfoFiles[0])

          $attrib = $attributeRegex.Match($fileContent) 

          $nativeVersion = $attrib.Groups[2].value

          Write-Host "AssemblyNativeVersion is $nativeVersion"

          Write-Host "$("##vso[task.setvariable variable=ASSEMBLY_NATIVE_VERSION]")$nativeVersion"
  condition: and( succeeded(), ne( variables['StartReleaseCandidate'], true ) )
  displayName: Get AssemblyNativeVersion version

- powershell: |
    # get subject and commit message for commit
    $commitMessage = git log --format='%B' -1

    # need to flatten message by removing new lines
    $commitMessage = $commitMessage -replace "`r`n", " "

    if($commitMessage -like "*PUBLISH_RELEASE*")
    {
      # set variable
      Write-Host "$("##vso[task.setvariable variable=RELEASE_DRAFT;isOutput=true]")false"
      Write-Host "$("##vso[task.setvariable variable=RELEASE_VERSION;isOutput=true]")true"
      Write-Host "Release draft: FALSE"
    }
    else
    {
      # set variable
      Write-Host "$("##vso[task.setvariable variable=RELEASE_DRAFT;isOutput=true]")true"
      Write-Host "$("##vso[task.setvariable variable=RELEASE_VERSION;isOutput=true]")false"
      Write-Host "Release draft: TRUE"
    }
  name: SetReleaseDraftVar
  condition: ne( variables['StartReleaseCandidate'], true )
  displayName: Set release draft var

- task: SonarCloudAnalyze@1
  condition: ne( variables['StartReleaseCandidate'], true )
  displayName: 'Run Code Analysis'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  condition: ne( variables['StartReleaseCandidate'], true )
  displayName: 'Publish Quality Gate Result'

# temporary disable of changelog generator
# - task: UseRubyVersion@0
#   inputs:
#     versionSpec: '= 2.4.6' 
#     addToPath: true
#   condition: and( succeeded(), not( startsWith(variables['Build.SourceBranch'], 'refs/pull') ), ne( variables['StartReleaseCandidate'], true ) )
#   displayName: Setup Ruby

# # generate change log
# - powershell: |
#       gem install github_changelog_generator --quiet --no-ri --no-rdoc
#       # need to call it passing both cache options with full path otherwise it won't work
#       github_changelog_generator --token $(GitHubToken) --cache-log  $env:AGENT_TEMPDIRECTORY\github-changelog-logger.log --cache-file $env:AGENT_TEMPDIRECTORY\github-changelog-http-cache --pr-wo-labels
#   condition: and( succeeded(), variables['SetReleaseDraftVar.RELEASE_DRAFT'], not( startsWith(variables['Build.SourceBranch'], 'refs/pull') ), not( startsWith(variables['Build.SourceBranch'], 'refs/tags/v') ), not( startsWith(variables['Build.SourceBranchName'], 'master') ), not( contains(variables['Build.SourceBranchName'], 'update-dependencies') ), ne( variables['StartReleaseCandidate'], true ) )
#   displayName: Generate change log

# # generate change log including future version
# - powershell: |
#       gem install github_changelog_generator --quiet --no-ri --no-rdoc
#       # need to call it passing both cache options with full path otherwise it won't work
#       github_changelog_generator --token $(GitHubToken) --cache-log  $env:AGENT_TEMPDIRECTORY\github-changelog-logger.log --cache-file $env:AGENT_TEMPDIRECTORY\github-changelog-http-cache --pr-wo-labels --future-release v$env:MY_NUGET_VERSION
#   condition: and( succeeded(), or( eq ( variables['SetReleaseDraftVar.RELEASE_VERSION'], 'True' ), and ( not( startsWith(variables['Build.SourceBranch'], 'refs/pull') ), not( startsWith(variables['Build.SourceBranch'], 'refs/tags/v') ), startsWith(variables['Build.SourceBranchName'], 'master'), not( contains(variables['Build.SourceBranchName'], 'update-dependencies') ) ) ), ne( variables['StartReleaseCandidate'], true ) )
#   displayName: Generate change log

# # copy change log to artifacts directory
# - task: CopyFiles@2
#   inputs:
#     SourceFolder: '$(System.DefaultWorkingDirectory)'
#     Contents: 'CHANGELOG.md'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'
#   condition: and( succeeded(), not( startsWith(variables['Build.SourceBranch'], 'refs/pull') ), not( contains(variables['Build.SourceBranchName'], 'update-dependencies') ), ne( variables['StartReleaseCandidate'], true ) )
#   displayName: Copy Changelog

# # push new changelog to GitHub repo
# - task: PowerShell@2
#   inputs:
#       targetType: 'inline'
#       script: |
#           git add CHANGELOG.md
#           git commit -m "Update CHANGELOG for v$(NBGV_Version)" -m"***NO_CI***"

#           git config user.email ${{ parameters.gitEmail }}
#           git config user.name ${{ parameters.gitUser }}
          
#           # compute authorization header in format "AUTHORIZATION: basic 'encoded token'"
#           # 'encoded token' is the Base64 of the string "nfbot:personal-token"
#           $auth = "basic $([System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("nfbot:$(GitHubToken)"))))"

#           git -c http.extraheader="AUTHORIZATION: $auth" push origin "HEAD:$(Build.SourceBranchName)"

#   condition: and( succeeded(), not( startsWith(variables['Build.SourceBranch'], 'refs/pull') ), not( startsWith(variables['Build.SourceBranch'], 'refs/tags/v') ), not( contains(variables['Build.SourceBranchName'], 'update-dependencies') ), ne( variables['StartReleaseCandidate'], true ) )
#   displayName: Push changelog to GitHub

# update could build number (only possible if this is not a PR from a fork)
- task: PowerShell@2
  inputs:
      targetType: 'inline'
      script: |
        Write-Host "$("##vso[build.updatebuildnumber]")$env:MY_NUGET_VERSION"
        Write-Host "Build version is $env:NBGV_AssemblyVersion"
  condition: and( succeeded(), ne(variables['system.pullrequest.isfork'], true), ne( variables['StartReleaseCandidate'], true ) )
  displayName: Update cloud build number

- task: NuGetCommand@2
  inputs:
    command: 'custom' 
    arguments: 'pack source\$(nugetPackageName).nuspec -Version $(MY_NUGET_VERSION) -properties nativeVersion="$(ASSEMBLY_NATIVE_VERSION)";commit="$(Build.SourceVersion)"'
  condition: and( succeeded(), ne( variables['StartReleaseCandidate'], true ) )
  displayName: Pack NuGet with class library

# - task: NuGetCommand@2
#   inputs:
#     command: 'custom' 
#     arguments: 'pack source\$(nugetPackageName).DELIVERABLES.nuspec -Version $(MY_NUGET_VERSION)'
#     displayName: Pack NuGet with build deliverables class library

- task: CopyFiles@1
  inputs:
    sourceFolder: $(Build.SourcesDirectory)
    Contents: |
      **\$(nugetPackageName)*.nupkg
      **\CHANGELOG.md
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true
  condition: and( succeeded(), ne( variables['StartReleaseCandidate'], true ) )
  displayName: Collecting deployable artifacts

# publish artifacts (only possible if this is not a PR originated on a fork)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: deployables
    ArtifactType: Container
  condition: and( succeeded(), ne(variables['system.pullrequest.isfork'], true), ne( variables['StartReleaseCandidate'], true ) )
  displayName: Publish deployables artifacts

# push NuGet packages to AzureArtifacts feed (always happens except on PR builds)
- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    publishFeedCredentials: 'AzureArtifacts-$(System.TeamProject)'
  condition: and( succeeded(), ne( variables['StartReleaseCandidate'], true ) )
  continueOnError: true
  displayName: Push NuGet packages to AzureArtifacts

# push NuGet class lib package to NuGet (happens on tag builds for any branch or when building a non draft release)
- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    allowPackageConflicts: true
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    publishFeedCredentials: 'NuGet-$(System.TeamProject)'
  condition: and( succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'), ne( variables['StartReleaseCandidate'], true ) )
  continueOnError: true
  displayName: Push NuGet packages to NuGet

# create or update GitHub release
- task: GitHubReleasePublish@1
  inputs:
    githubEndpoint: 'nanoframework'
    githubOwner: 'nanoframework'
    githubRepositoryName: $(repoName)
    githubTag: v$(MY_NUGET_VERSION)
    githubReleaseTitle: '$(nugetPackageName) Library v$(MY_NUGET_VERSION)'
    githubReleaseNotes: 'Check the [changelog]($(Build.Repository.Uri)/blob/$(Build.SourceBranchName)/CHANGELOG.md).<br><br><h4>Install from nanoFramework Azure DevOps development feed</h4><br>The following NuGet packages are available for download from this release:<br>:package: [.NET](https://dev.azure.com/nanoframework/feed/_packaging?_a=package&feed=sandbox&view=overview&package=$(nugetPackageName)&protocolType=NuGet&version=$(MY_NUGET_VERSION)) v$(MY_NUGET_VERSION).'
    githubTargetCommitsh: $(Build.SourceVersion)
    githubReleaseDraft: $(RELEASE_DRAFT)
    githubReleasePrerelease: true
    githubReuseDraftOnly: false
    githubReuseRelease: true
    githubEditRelease: true
    githubDeleteEmptyTag: true
    githubReleaseAsset: '$(Build.ArtifactStagingDirectory)/$(nugetPackageName).$(MY_NUGET_VERSION).nupkg'
  condition: and( succeeded(), not( startsWith(variables['Build.SourceBranch'], 'refs/pull') ), not( startsWith(variables['Build.SourceBranch'], 'refs/tags/v') ), ne( variables['StartReleaseCandidate'], true ) )
  displayName: Create/Update GitHub release

# create or update GitHub release ON tags from release or master branches
- task: GitHubReleasePublish@1
  inputs:
    githubEndpoint: 'nanoframework'
    githubOwner: 'nanoframework'
    githubRepositoryName: $(repoName)
    githubTag: v$(MY_NUGET_VERSION)
    githubReleaseTitle: '$(nugetPackageName) Library v$(MY_NUGET_VERSION)'
    githubReleaseNotes: 'Check the [changelog]($(Build.Repository.Uri)/blob/$(Build.SourceBranchName)/CHANGELOG.md).<br><br><h4>Install from NuGet</h4><br>The following NuGet packages are available for download from this release:<br>:package: [.NET](https://www.nuget.org/packages/$(nugetPackageName)/$(MY_NUGET_VERSION)) v$(MY_NUGET_VERSION).'
    githubTargetCommitsh: $(Build.SourceVersion)
    githubReleaseDraft: $(RELEASE_DRAFT)
    githubReleasePrerelease: true
    githubReuseDraftOnly: false
    githubReuseRelease: true
    githubEditRelease: true
    githubDeleteEmptyTag: true
    githubReleaseAsset: '$(Build.ArtifactStagingDirectory)/$(nugetPackageName).$(MY_NUGET_VERSION).nupkg'
  condition: and( succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'), contains(variables['Build.SourceBranch'], 'preview'), ne( variables['StartReleaseCandidate'], true ) )
  displayName: Create/Update GitHub PREVIEW release 

# create or update GitHub release ON tags from release or master branches
- task: GitHubReleasePublish@1
  inputs:
    githubEndpoint: 'nanoframework'
    githubOwner: 'nanoframework'
    githubRepositoryName: $(repoName)
    githubTag: v$(MY_NUGET_VERSION)
    githubReleaseTitle: '$(nugetPackageName) Library v$(MY_NUGET_VERSION)'
    githubReleaseNotes: 'Check the [changelog]($(Build.Repository.Uri)/blob/$(Build.SourceBranchName)/CHANGELOG.md).<br><br><h4>Install from NuGet</h4><br>The following NuGet packages are available for download from this release:<br>:package: [.NET](https://www.nuget.org/packages/$(nugetPackageName)/$(MY_NUGET_VERSION)) v$(MY_NUGET_VERSION).'
    githubTargetCommitsh: $(Build.SourceVersion)
    githubReleaseDraft: false
    githubReleasePrerelease: false
    githubReuseDraftOnly: false
    githubReuseRelease: true
    githubEditRelease: false
    githubDeleteEmptyTag: true
    githubReleaseAsset: '$(Build.ArtifactStagingDirectory)/$(nugetPackageName).$(MY_NUGET_VERSION).nupkg'
  condition: and( succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'), not(contains(variables['Build.SourceBranch'], 'preview') ), ne( variables['StartReleaseCandidate'], true ) )
  displayName: Create/Update GitHub stable release
