# Copyright (c) 2019 The nanoFramework project contributors
# Portions Copyright (c) Sankarsan Kampa (a.k.a. k3rn31p4nic).  All rights reserved.
# See LICENSE file in the project root for full license information.

parameters:
  skipNuGetRestore: false
  gitUser: 'nfbot'
  gitEmail: 'nanoframework@outlook.com'
  sonarCloudProject: 'dummy-key'
  nugetConfigPath: 'source/NuGet.config'

steps:
# need this here in order to persist GitHub credentials 
- checkout: self

- script: |
    git config --global user.email ${{ parameters.gitEmail }}
    git config --global user.name ${{ parameters.gitUser }}
    git config --global core.autocrlf true
  displayName: Setup git identity

# get commit message
- powershell: |

    if($env:Build_SourceBranch -like "refs/pull*")
    {
      # PR build, get PR message

      # need to get PR number from branch as the Azure Pipeline var can't be trusted
      if($env:Build_SourceBranch -match '(?<=(pull\/))\w*(?=(\/))')
      {
        $prNumber = $matches[0]

        $prUrl = "https://api.github.com/repos/$env:Build_Repository_Name/pulls/$prNumber"

        $commit = Invoke-RestMethod -Uri $prUrl -ContentType "application/json" -Method GET

        $commitMessage = $commit.body
      }
    }
    else
    {
      # not a PR, get subject and commit message for commit
      $commitMessage = git log --format='%B' -1
    }

    # need to flatten message by removing new lines
    $commitMessage = $commitMessage -replace "`r`n", " "

    # set variable to foward to jobs
    echo "##vso[task.setvariable variable=COMMIT_MESSAGE;isOutput=true]$commitMessage"
  name: getCommitMessage
  displayName: grab commit message

- task: DotNetCoreCLI@2  
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  condition: or( variables['START_RELEASE_CANDIDATE'], ne(variables['system.pullrequest.isfork'], true) )
  displayName: Install NBGV tool

- script: |
    cd source > $null
    nbgv prepare-release ${{ parameters.nbgvParameters }}
  condition: variables['START_RELEASE_CANDIDATE']
  displayName: NBGV prepare release

- script: |

    # get commit message for the merge
    $commitMessage = git log -1 --pretty=%B

    # amend commit message to skip build
    git commit --amend -m "$commitMessage" -m "***NO_CI***" > $null

    # compute authorization header in format "AUTHORIZATION: basic 'encoded token'"
    # 'encoded token' is the Base64 of the string "nfbot:personal-token"
    $auth = "basic $([System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("nfbot:$(GitHubToken)"))))"

    git -c http.extraheader="AUTHORIZATION: $auth" push --all origin
  condition: variables['START_RELEASE_CANDIDATE']
  displayName: Push all changes to GitHub

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'nanoframework'
    scannerMode: 'MSBuild'
    projectKey: '${{ parameters.sonarCloudProject }}'
  condition: not(variables['START_RELEASE_CANDIDATE'])
  displayName: 'Prepare analysis on SonarCloud'

- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '4.9.3'
  condition: not(variables['START_RELEASE_CANDIDATE'])
  displayName: 'Install specifc version of NuGet'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: config
    nugetConfigPath: ${{ parameters.nugetConfigPath }}
  condition: and( succeeded(), not( ${{ parameters.skipNuGetRestore }} ), not(variables['START_RELEASE_CANDIDATE']) )
  displayName: NuGet restore

- task: InstallnFBuildComponents@1
  condition: not(variables['START_RELEASE_CANDIDATE'])
  displayName: Install nanoFramework MSBuild components

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    msbuildArgs: '/p:PublicRelease=true'
    configuration: '$(buildConfiguration)'
  condition: not(variables['START_RELEASE_CANDIDATE'])

# we don't have tests (yet)
# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
#   condition: not(variables['START_RELEASE_CANDIDATE'])

- task: PowerShell@2
  inputs:
      targetType: 'inline'
      script: |
          $MyNuGetVersion = $env:NBGV_NuGetPackageVersion -replace "\-g$env:NBGV_GitCommitIdShort", ""

          # replace preview with alpha if this is a PR build
          if($env:Build_Reason -eq 'PullRequest')
          {
            $MyNuGetVersion = $MyNuGetVersion -replace "preview", "alpha"
          }

          Write-Host "NuGet build number is $MyNuGetVersion"

          Write-Host "$("##vso[task.setvariable variable=MY_NUGET_VERSION]")$MyNuGetVersion"
  condition: and( succeeded(), not(variables['START_RELEASE_CANDIDATE']) )
  displayName: Get NuGet build number

- task: PowerShell@2
  inputs:
      targetType: 'inline'
      script: |

          $assemblyInfoFiles = (Get-ChildItem -Path ".\*" -Include "AssemblyInfo.cs" -Recurse)
          $attributeRegex = '(AssemblyNativeVersion\(\")+(\d+\.\d+\.\d+\.\d)+("\))'

          $attributeRegex = [regex]"(AssemblyNativeVersion\(\"")+(\d+\.\d+\.\d+\.\d)+(""\))"

          # read attribute from file
          $fileContent = Get-Content($assemblyInfoFiles[0])

          $attrib = $attributeRegex.Match($fileContent) 

          $nativeVersion = $attrib.Groups[2].value

          Write-Host "AssemblyNativeVersion is $nativeVersion"

          Write-Host "$("##vso[task.setvariable variable=ASSEMBLY_NATIVE_VERSION]")$nativeVersion"
  condition: and( succeeded(), not(variables['START_RELEASE_CANDIDATE']) )
  displayName: Get AssemblyNativeVersion version

- powershell: |
    # get subject and commit message for commit
    $commitMessage = git log --format='%B' -1

    # need to flatten message by removing new lines
    $commitMessage = $commitMessage -replace "`r`n", " "

    if($commitMessage -like "*PUBLISH_RELEASE*")
    {
      # set variable
      Write-Host "$("##vso[task.setvariable variable=RELEASE_DRAFT;isOutput=true]")False"
      Write-Host "$("##vso[task.setvariable variable=RELEASE_VERSION;isOutput=true]")True"
      Write-Host "Release draft: FALSE"
    }
    else
    {
      # set variable
      Write-Host "$("##vso[task.setvariable variable=RELEASE_DRAFT;isOutput=true]")True"
      Write-Host "$("##vso[task.setvariable variable=RELEASE_VERSION;isOutput=true]")False"
      Write-Host "Release draft: TRUE"
    }
  name: SetReleaseDraftVar
  condition: not(variables['START_RELEASE_CANDIDATE'])
  displayName: Set release draft var

- task: SonarCloudAnalyze@1
  condition: not(variables['START_RELEASE_CANDIDATE'])
  displayName: 'Run Code Analysis'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  condition: not(variables['START_RELEASE_CANDIDATE'])
  displayName: 'Publish Quality Gate Result'

- task: UseRubyVersion@0
  inputs:
    versionSpec: '= 2.5' 
    addToPath: true
  condition: and( succeeded(), not( startsWith(variables['Build.SourceBranch'], 'refs/pull') ), not(variables['START_RELEASE_CANDIDATE']) )
  displayName: Setup Ruby

# generate change log
- powershell: |
      gem install github_changelog_generator --quiet --no-ri --no-rdoc
      # need to call it passing both cache options with full path otherwise it won't work
      github_changelog_generator --token $(GitHubToken) --cache-log  $env:AGENT_TEMPDIRECTORY\github-changelog-logger.log --cache-file $env:AGENT_TEMPDIRECTORY\github-changelog-http-cache
  condition: and( succeeded(), variables['SetReleaseDraftVar.RELEASE_DRAFT'], not( startsWith(variables['Build.SourceBranch'], 'refs/pull') ), not( startsWith(variables['Build.SourceBranch'], 'refs/tags/v') ), not( startsWith(variables['Build.SourceBranchName'], 'master') ), not( contains(variables['Build.SourceBranchName'], 'update-dependencies') ), not(variables['START_RELEASE_CANDIDATE']) )
  displayName: Generate change log

# generate change log including future version
- powershell: |
      gem install github_changelog_generator --quiet --no-ri --no-rdoc
      # need to call it passing both cache options with full path otherwise it won't work
      github_changelog_generator --token $(GitHubToken) --cache-log  $env:AGENT_TEMPDIRECTORY\github-changelog-logger.log --cache-file $env:AGENT_TEMPDIRECTORY\github-changelog-http-cache --future-release v$env:MY_NUGET_VERSION
  condition: and( succeeded(), or( variables['SetReleaseDraftVar.RELEASE_VERSION'], and ( not( startsWith(variables['Build.SourceBranch'], 'refs/pull') ), not( startsWith(variables['Build.SourceBranch'], 'refs/tags/v') ), startsWith(variables['Build.SourceBranchName'], 'master'), not( contains(variables['Build.SourceBranchName'], 'update-dependencies') ) ) ), not(variables['START_RELEASE_CANDIDATE']) )
  displayName: Generate change log

# copy change log to artifacts directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: 'CHANGELOG.md'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  condition: and( succeeded(), not( startsWith(variables['Build.SourceBranch'], 'refs/pull') ), not( contains(variables['Build.SourceBranchName'], 'update-dependencies') ), not(variables['START_RELEASE_CANDIDATE']) )
  displayName: Copy Changelog

# push new changelog to GitHub repo
- task: PowerShell@2
  inputs:
      targetType: 'inline'
      script: |
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG for v$(NBGV_Version)" -m"***NO_CI***"

          git config user.email ${{ parameters.gitEmail }}
          git config user.name ${{ parameters.gitUser }}
          
          # compute authorization header in format "AUTHORIZATION: basic 'encoded token'"
          # 'encoded token' is the Base64 of the string "nfbot:personal-token"
          $auth = "basic $([System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("nfbot:$(GitHubToken)"))))"

          git -c http.extraheader="AUTHORIZATION: $auth" push origin "HEAD:$(Build.SourceBranchName)"

  condition: and( succeeded(), not( startsWith(variables['Build.SourceBranch'], 'refs/pull') ), not( startsWith(variables['Build.SourceBranch'], 'refs/tags/v') ), not( contains(variables['Build.SourceBranchName'], 'update-dependencies') ), not(variables['START_RELEASE_CANDIDATE']) )
  displayName: Push changelog to GitHub

# update could build number (only possible if this is not a PR from a fork)
- task: PowerShell@2
  inputs:
      targetType: 'inline'
      script: Write-Host "$("##vso[build.updatebuildnumber]")$env:NBGV_NuGetPackageVersion"
  condition: and( succeeded(), ne(variables['system.pullrequest.isfork'], true), not(variables['START_RELEASE_CANDIDATE']) )
  displayName: Update cloud build number

- task: CopyFiles@1
  inputs:
    sourceFolder: $(Build.SourcesDirectory)
    Contents: |
      **\CHANGELOG.md
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true
  condition: and( succeeded(), not(variables['START_RELEASE_CANDIDATE']) )
  displayName: Collecting deployable artifacts

