# Copyright (c) 2019 The nanoFramework project contributors
# Portions Copyright (c) Sankarsan Kampa (a.k.a. k3rn31p4nic).  All rights reserved.
# See LICENSE file in the project root for full license information.

parameters:
  nugetPackageName: ''

steps:

- task: PowerShell@2
  inputs:
      targetType: 'inline'
      script: |
          $nupecFiles = (Get-ChildItem -Path ".\*" -Include "*.nuspec" -Recurse)

          foreach($file in $nupecFiles)
          {
              Write-Debug "Updating source file with assembly declaration: $file."

              # update release notes with native assembly version
              $filecontent = Get-Content($file)
              attrib $file -r
              $filecontent -replace  "\$nativeVersion\$", "$(ASSEMBLY_NATIVE_VERSION)" | Out-File $file -Encoding utf8
          }
  condition: succeeded()
  displayName: Add native assembly version to NuGet release notes

- task: NuGetCommand@2
  inputs:
    command: 'custom' 
    arguments: 'pack source\${{ parameters.nugetPackageName }}.nuspec -Version $(MY_NUGET_VERSION) -Symbols'
  condition: succeeded()
  displayName: Pack NuGet with class library

- task: CopyFiles@1
  inputs:
    sourceFolder: $(Build.SourcesDirectory)
    Contents: |
      **\${{ parameters.nugetPackageName }}*.nupkg
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true
  condition: succeeded()
  displayName: Collecting deployable artifacts
