# Copyright (c) 2020 The nanoFramework project contributors
# See LICENSE file in the project root for full license information.

steps:

  - task: DotNetCoreCLI@2  
    inputs:
      command: custom
      custom: tool
      arguments: install -g nbgv
    condition: or( eq( variables['StartReleaseCandidate'], true ), ne(variables['system.pullrequest.isfork'], true) )
    displayName: Install NBGV tool
