# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

steps:

  - task: DotNetCoreCLI@2  
    displayName: Install NBGV tool
    inputs:
      command: custom
      custom: tool
      arguments: install -g nbgv

  - script: nbgv cloud -a -c
    displayName: Set build number

  - task: PowerShell@2
    condition: and( succeeded(), ne( variables['StartReleaseCandidate'], true ) )
    displayName: Get NuGet build number
    inputs:
      targetType: 'inline'
      script: |
        $MyNuGetVersion = $env:NBGV_NuGetPackageVersion -replace ".g$env:NBGV_GitCommitIdShort", ""

        # replace preview with alpha if this is a PR build
        if($env:System_PullRequest_PullRequestId -ne $null)
        {
            # mix PR and VersionHeight
            $alphaNumber = [int]$env:System_PullRequest_PullRequestNumber + $env:NBGV_VersionHeight;

            $alphaPrString = "alpha." + $alphaNumber.ToString()
            $MyNuGetVersion = $MyNuGetVersion -replace "preview", $alphaPrString
        }
        if ($env:System_PullRequest_SourceBranch -like 'release*')
        {
            $MyNuGetVersion = $MyNuGetVersion + "-rc." + $env:NBGV_VersionHeight
        }

        Write-Host "NuGet build is: $MyNuGetVersion"
        Write-Host "Assembly version is: $env:NBGV_AssemblyVersion"

        Write-Host "$("##vso[task.setvariable variable=MY_NUGET_VERSION]")$MyNuGetVersion"
