# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

parameters:
  forceRun: false

steps:
- task: PowerShell@2
  displayName: Report build failure
  condition: or( failed(), eq( ${{ parameters.forceRun }}, true ) )
  inputs:
    errorActionPreference: 'silentlyContinue'    
    targetType: 'inline'
    script: |

      Install-Module -Name PowerShellForGitHub -Scope CurrentUser -Force

      $secureString = ("$(GitHubToken)" | ConvertTo-SecureString -AsPlainText -Force)
      $cred = New-Object System.Management.Automation.PSCredential "username is ignored", $secureString
      Set-GitHubAuthentication -Credential $cred -SessionOnly

      # check if this is a PR
      if($env:System_PullRequest_PullRequestId -ne $null)
      {
          Write-Host "Building from PR $env:System_PullRequest_PullRequestId"

          $pr = Get-GitHubIssue -Uri "https://github.com/$env:Build_Repository_Name" -Issue $env:System_PullRequest_PullRequestNumber

          $user = [String]$pr.user.login

          # only warn user if it's NOT an automated build
          if($user -eq 'nfbot' -or $user -eq 'github-actions[bot]' -or $user -eq 'dependabot[bot]')
          {
              Write-Host "Skipping warning"
          }
          else
          {
              Write-Host "Sending warning to $user"

              $comment = New-GitHubIssueComment -Uri "https://github.com/$env:Build_Repository_Name" -Issue $env:System_PullRequest_PullRequestNumber -Body "Hey @$user!`n`nSeems that the build is failing for this PR... :disappointed: Please check it."

              $commentId = [String]$comment.CommentId 
              Write-Host "Adding comment $commentId"

              # need to wait a few seconds, otherwise github won't pickup the comment for sending
              Start-Sleep -Seconds 10

              Remove-GitHubIssueComment -Uri "https://github.com/$env:Build_Repository_Name" -CommentID $commentId -Force

              Write-Host "Removed comment"
          }
      }
      else
      {
          Write-Host "Building from other than PR. Nothing to do here."
      }
