# Do not build branches of the form "pr/*". By prefixing pull requests coming
# from branches inside the repository with pr/, this avoids building both the
# branch push _and_ the pull request.
branches:
  except: /pr\/.*/

os:
  - linux

language: csharp

solution: restore nanoFramework.Tools.Hex2Dfu/nanoFramework.Tools.Hex2Dfu.sln

install:
  - nuget restore restore nanoFramework.Tools.Hex2Dfu/nanoFramework.Tools.Hex2Dfu.sln

script:
  - xbuild /p:Configuration=Release nanoFramework.Tools.Hex2Dfu/nanoFramework.Tools.Hex2Dfu.sln
