version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
clone_depth: 1

build_script:
- ps: >-
    nuget restore nanoFramework.Tools.Hex2Dfu\nanoFramework.Tools.Hex2Dfu.sln

    msbuild nanoFramework.Tools.Hex2Dfu\nanoFramework.Tools.Hex2Dfu.sln /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
- path: '**\bin\Release\hex2dfu.exe'
  name: hex2dfu_executable

deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: nanoFramework Tools v$(appveyor_build_version)
  description: add description here
  auth_token:
    secure: DNixoFFE+pGlwyhj7McfZoln42vOmj0iY1iNV9zXEr3y0NpXlOIgL8k5ehzlFM1S
  artifact: hex2dfu_executable
  draft: true
  prerelease: true
  force_update: true
