##
# Performs checkout step
##
name: Checkout repo

on:
  workflow_call:

jobs:
  perform_checkout:
    name: Checkout repository
    timeout-minutes: 5
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
