# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.
name: Build and deploy nanoFramework GitHubBot
on:
  push:
    branches:
      - main
    paths:
      - github-nfbot/GitHub-nfbot/**
env:
  AZURE_FUNCTIONAPP_NAME: NanoFramework-GitHubBot
  AZURE_FUNCTIONAPP_PACKAGE_PATH: .\published
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.x
  WORKING_DIRECTORY: .
  DOTNET_CORE_VERSION_INPROC: ''
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Setup .NET Core (for inproc extensions)
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION_INPROC }}
    - name: Restore
      run: dotnet restore "github-nfbot/GitHub-nfbot"
    - name: Build
      run: dotnet build "github-nfbot/GitHub-nfbot" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish
      run: dotnet publish "github-nfbot/GitHub-nfbot" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.NANOFRAMEWORK_GITHUBBOT_FFFF }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
